#!/usr/bin/env ruby
# frozen_string_literal: true

require 'email_report_processor'

require 'optparse'

options = {
  class: nil,
  mbox:  false,
  os:    {},
}

OptionParser.new do |opts|
  opts.banner = "usage: #{$PROGRAM_NAME} [options] [file...]"
  opts.separator("\nReport type selection:")
  opts.on('--dmarc', 'Process DMARC Reports') do
    options[:class] = EmailReportProcessor::DmarcRua
  end
  opts.on('--tlsrpt', 'Process SMTP TLS Reports') do
    options[:class] = EmailReportProcessor::TlsrptRua
  end
  opts.separator("\nOpenSearch options:")
  opts.on('-h', '--os-hostname=HOSTNAME', 'Hostname of the OpenSearch instance') do |hostname|
    options[:os][:hostname] = hostname
  end
  opts.on('-p', '--os-port=PORT', 'Port of the OpenSearch instance') do |port|
    options[:os][:port] = port.to_i
  end
  opts.on('-u', '--os-username=USERNAME', 'Username of the OpenSearch instance') do |username|
    options[:os][:username] = username
  end
  opts.on('--os-password=PASSWORD', 'Password of the OpenSearch instance') do |password|
    options[:os][:password] = password
  end

  opts.separator("\nMiscellaneous options:")
  opts.on('--mbox', 'Treat the provided file as a mailbox') do
    options[:mbox] = true
  end
end.parse!

if options[:class].nil?
  warn('A processor type must be passed')
  exit 1
end

processor = options[:class].new(**options[:os])

if ARGV.empty?
  mail = Mail.new($stdin.read)
  processor.process_message(mail)
else
  ARGV.each do |filename|
    if options[:mbox]
      m = EmailReportProcessor::MailBox.new(filename)

      while (message = m.next_message)
        mail = Mail.new(message)
        processor.process_message(mail)
      end
    else
      mail = Mail.new(File.read(filename))
      processor.process_message(mail)
    end
  end
end
